// <auto-generated />
namespace MVC1_BookWorld.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Datedatatypesettostring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Datedatatypesettostring));
        
        string IMigrationMetadata.Id
        {
            get { return "201903082023257_Date datatype set to string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
