// <auto-generated />
namespace MVC1_BookWorld.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class seeding_CanManageBooks_Admin_CanManageCustomers_AdminAndStaff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seeding_CanManageBooks_Admin_CanManageCustomers_AdminAndStaff));
        
        string IMigrationMetadata.Id
        {
            get { return "201906241547557_seeding_CanManageBooks_Admin_CanManageCustomers_AdminAndStaff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
